// <auto-generated>
//     Generated by ConFigTree 0.2.0
//     https://rpapub.github.io/ConFigTree/
// </auto-generated>

#nullable enable

using System;
using System.Data;
using System.Collections.Generic;

namespace Cpmf.Config
{
    /// <summary>Root configuration object.</summary>
    public class CodedConfig
    {
        public AssetsConfig Assets { get; set; } = new();
        public override string ToString() =>
            $"CodedConfig {{ Assets={Assets} }}";

        public static CodedConfig Load(Dictionary<string, DataTable> tables)
        {
            var cfg = new CodedConfig();
            // "Assets": asset values are fetched from Orchestrator via GetRobotAsset in the generated XAML snippet — not loaded from DataTable.
            return cfg;
        }
    }

    public class AssetsConfig
    {
        /// <summary>Queue name.</summary>
        public string QueueName { get; set; } = "";
        /// <summary>Upper bound.</summary>
        public int MaxItems { get; set; }
        /// <summary>Enable strict.</summary>
        public bool StrictMode { get; set; }
        /// <summary>Untyped fallback.</summary>
        public object? GenericValue { get; set; }

        public override string ToString() =>
            $"AssetsConfig {{ QueueName={QueueName}, MaxItems={MaxItems}, StrictMode={StrictMode}, GenericValue={GenericValue} }}";
    }
}