// <auto-generated>
//     Generated by ConFigTree 0.2.0
//     https://rpapub.github.io/ConFigTree/
// </auto-generated>

#nullable enable

using System;
using System.Data;
using System.Collections.Generic;

namespace Cpmf.Config
{
    /// <summary>Root configuration object.</summary>
    public class CodedConfig
    {
        public EmptySheetConfig EmptySheet { get; set; } = new();
        public NoHeaderConfig NoHeader { get; set; } = new();
        public SettingsConfig Settings { get; set; } = new();
        public override string ToString() =>
            $"CodedConfig {{ EmptySheet={EmptySheet}, NoHeader={NoHeader}, Settings={Settings} }}";

        public static CodedConfig Load(Dictionary<string, DataTable> tables)
        {
            var cfg = new CodedConfig();
            if (tables.TryGetValue("Settings", out var t_Settings)) cfg.Settings = SettingsConfig.FromDataTable(t_Settings);
            return cfg;
        }
    }

    public class EmptySheetConfig
    {
        // No data rows found in source sheet.
    }

    public class NoHeaderConfig
    {
        // No data rows found in source sheet.
    }

    public class SettingsConfig
    {
        /// <summary>A valid setting.</summary>
        public string QueueName { get; set; } = "TestQueue";

        public static SettingsConfig FromDataTable(DataTable dt)
        {
            var cfg = new SettingsConfig();
            foreach (DataRow row in dt.Rows)
            {
                if (row.ItemArray.Length < 2) continue;
                var key   = row[0]?.ToString()?.Trim();
                var value = row[1]?.ToString()?.Trim() ?? "";
                switch (key)
                {
                    case "QueueName": cfg.QueueName = value; break;
                }
            }
            return cfg;
        }

        public override string ToString() =>
            $"SettingsConfig {{ QueueName={QueueName} }}";
    }
}