// <auto-generated>
//     Generated by ConFigTree 0.2.0
//     https://rpapub.github.io/ConFigTree/
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace Cpmf.Config
{
    /// <summary>Root configuration object.</summary>
    public class CodedConfig
    {
        public SettingsConfig Settings { get; set; } = new();
        public ConstantsConfig Constants { get; set; } = new();
        public AssetsConfig Assets { get; set; } = new();
        public override string ToString() =>
            $"CodedConfig {{ Settings={Settings}, Constants={Constants}, Assets={Assets} }}";

        public static CodedConfig LoadJson(string filePath)
        {
            var json = System.IO.File.ReadAllText(filePath);
            return System.Text.Json.JsonSerializer.Deserialize<CodedConfig>(json)
                ?? throw new InvalidOperationException("Failed to deserialize config.");
        }
    }

    public class SettingsConfig
    {
        /// <summary>Orchestrator queue name.</summary>
        public string OrchestratorQueueName { get; set; } = "BasicQueue";
        /// <summary>Orchestrator folder path.</summary>
        public string OrchestratorFolderPath { get; set; } = "RPA/Basic";
        /// <summary>Max items to process per run.</summary>
        public int MaxItemsPerRun { get; set; } = 10;
        /// <summary>Number of retries on failure.</summary>
        public int RetryCount { get; set; } = 3;
        /// <summary>Prefix for log messages.</summary>
        public string LogPrefix { get; set; } = "BASIC";

        public override string ToString() =>
            $"SettingsConfig {{ OrchestratorQueueName={OrchestratorQueueName}, OrchestratorFolderPath={OrchestratorFolderPath}, MaxItemsPerRun={MaxItemsPerRun}, RetryCount={RetryCount}, LogPrefix={LogPrefix} }}";
    }

    public class ConstantsConfig
    {
        /// <summary>Must be 0 when using Orchestrator queues.</summary>
        public int MaxRetryNumber { get; set; } = 0;
        /// <summary>Stop job after this many consecutive errors.</summary>
        public int MaxConsecutiveSystemExceptions { get; set; } = 3;
        /// <summary>Retries for GetTransactionItem activity.</summary>
        public int RetryNumberGetTransactionItem { get; set; } = 2;

        public override string ToString() =>
            $"ConstantsConfig {{ MaxRetryNumber={MaxRetryNumber}, MaxConsecutiveSystemExceptions={MaxConsecutiveSystemExceptions}, RetryNumberGetTransactionItem={RetryNumberGetTransactionItem} }}";
    }

    public class AssetsConfig
    {
        /// <summary>M365 service credential.</summary>
        public object? CredentialM365 { get; set; }
        /// <summary>FTP server credential.</summary>
        public object? CredentialFtp { get; set; }

        public override string ToString() =>
            $"AssetsConfig {{ CredentialM365={CredentialM365}, CredentialFtp={CredentialFtp} }}";
    }
}