// <auto-generated>
//     Generated by ConFigTree 0.2.0
//     https://rpapub.github.io/ConFigTree/
// </auto-generated>

#nullable enable

using System;
using System.Data;
using System.Collections.Generic;

namespace Cpmf.Config
{
    /// <summary>Root configuration object.</summary>
    public class CodedConfig
    {
        public SettingsConfig Settings { get; set; } = new();
        public ConstantsConfig Constants { get; set; } = new();
        public AssetsConfig Assets { get; set; } = new();
        public override string ToString() =>
            $"CodedConfig {{ Settings={Settings}, Constants={Constants}, Assets={Assets} }}";

        public static CodedConfig Load(Dictionary<string, DataTable> tables)
        {
            var cfg = new CodedConfig();
            if (tables.TryGetValue("Settings", out var t_Settings)) cfg.Settings = SettingsConfig.FromDataTable(t_Settings);
            if (tables.TryGetValue("Constants", out var t_Constants)) cfg.Constants = ConstantsConfig.FromDataTable(t_Constants);
            // "Assets": asset values are fetched from Orchestrator via GetRobotAsset in the generated XAML snippet — not loaded from DataTable.
            return cfg;
        }
    }

    public class SettingsConfig
    {
        /// <summary>Deployment environment.</summary>
        public string Environment { get; set; } = "UAT";
        /// <summary>Minimum log level.</summary>
        public string LogLevel { get; set; } = "Info";

        public static SettingsConfig FromDataTable(DataTable dt)
        {
            var cfg = new SettingsConfig();
            foreach (DataRow row in dt.Rows)
            {
                if (row.ItemArray.Length < 2) continue;
                var key   = row[0]?.ToString()?.Trim();
                var value = row[1]?.ToString()?.Trim() ?? "";
                switch (key)
                {
                    case "Environment": cfg.Environment = value; break;
                    case "LogLevel": cfg.LogLevel = value; break;
                }
            }
            return cfg;
        }

        public override string ToString() =>
            $"SettingsConfig {{ Environment={Environment}, LogLevel={LogLevel} }}";
    }

    public class ConstantsConfig
    {
        /// <summary>Must be 0 when using Orchestrator queues.</summary>
        public int MaxRetryNumber { get; set; } = 0;

        public static ConstantsConfig FromDataTable(DataTable dt)
        {
            var cfg = new ConstantsConfig();
            foreach (DataRow row in dt.Rows)
            {
                if (row.ItemArray.Length < 2) continue;
                var key   = row[0]?.ToString()?.Trim();
                var value = row[1]?.ToString()?.Trim() ?? "";
                switch (key)
                {
                    case "MaxRetryNumber":
                        if (int.TryParse(value, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out var v_MaxRetryNumber)) cfg.MaxRetryNumber = v_MaxRetryNumber;
                        break;
                }
            }
            return cfg;
        }

        public override string ToString() =>
            $"ConstantsConfig {{ MaxRetryNumber={MaxRetryNumber} }}";
    }

    public class AssetsConfig
    {
        /// <summary>SAP system credential.</summary>
        public object? CredentialSap { get; set; }
        /// <summary>M365 credential.</summary>
        public object? CredentialM365 { get; set; }
        /// <summary>FTP server credential.</summary>
        public object? CredentialFtp { get; set; }
        /// <summary>Payment gateway API key.</summary>
        public object? ApiKeyPayment { get; set; }

        public override string ToString() =>
            $"AssetsConfig {{ CredentialSap={CredentialSap}, CredentialM365={CredentialM365}, CredentialFtp={CredentialFtp}, ApiKeyPayment={ApiKeyPayment} }}";
    }
}