// <auto-generated>
//     Generated by ConFigTree 0.2.0
//     https://rpapub.github.io/ConFigTree/
// </auto-generated>

#nullable enable

using System;
using System.Data;
using System.Collections.Generic;

namespace Cpmf.Config
{
    /// <summary>Root configuration object.</summary>
    public class CodedConfig
    {
        public SAPConfig SAP { get; set; } = new();
        public override string ToString() =>
            $"CodedConfig {{ SAP={SAP} }}";

        public static CodedConfig Load(Dictionary<string, DataTable> tables)
        {
            var cfg = new CodedConfig();
            if (tables.TryGetValue("SAP", out var t_SAP)) cfg.SAP = SAPConfig.FromDataTable(t_SAP);
            return cfg;
        }
    }

    public class SAPConfig
    {
        /// <summary>SAP application server hostname.</summary>
        public string Host { get; init; } = "sap.example.com";
        /// <summary>SAP system number.</summary>
        public int Port { get; init; } = 3200;
        /// <summary>Orchestrator credential asset name. When set, Username and Password are ignored.</summary>
        public string CredentialAsset { get; init; } = "";
        public string CredentialAssetFolder => CredentialAsset.Contains('/') ? CredentialAsset.Split('/')[0] : "";
        public string CredentialAssetName   => CredentialAsset.Contains('/') ? CredentialAsset.Split('/')[1] : CredentialAsset;

        public static SAPConfig FromDataTable(DataTable dt)
        {
            string loc_Host = "";
            int loc_Port = 0;
            string loc_CredentialAsset = "";
            foreach (DataRow row in dt.Rows)
            {
                if (row.ItemArray.Length < 2) continue;
                var key   = row[0]?.ToString()?.Trim();
                var value = row[1]?.ToString()?.Trim() ?? "";
                switch (key)
                {
                    case "Host": loc_Host = value; break;
                    case "Port":
                        if (int.TryParse(value, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out var tmp_Port)) loc_Port = tmp_Port;
                        break;
                    case "CredentialAsset": loc_CredentialAsset = value; break;
                }
            }
            return new SAPConfig
            {
                Host = loc_Host,
                Port = loc_Port,
                CredentialAsset = loc_CredentialAsset,
            };
        }

        public override string ToString() =>
            $"SAPConfig {{ Host={Host}, Port={Port}, CredentialAsset={CredentialAsset} }}";
    }
}