// <auto-generated>
//     Generated by ConFigTree 0.2.0
//     https://rpapub.github.io/ConFigTree/
// </auto-generated>

#nullable enable

using System;
using System.Data;
using System.Collections.Generic;

namespace Cpmf.Config
{
    /// <summary>Root configuration object.</summary>
    public class CodedConfig
    {
        public _2024Q1Config _2024Q1 { get; set; } = new();
        public BadSheetConfig BadSheet { get; set; } = new();
        public IdentifierConfig Identifier { get; set; } = new();
        public MySectionConfig MySection { get; set; } = new();
        public MySection_2Config MySection_2 { get; set; } = new();
        public BadAssetsConfig BadAssets { get; set; } = new();
        public override string ToString() =>
            $"CodedConfig {{ _2024Q1={_2024Q1}, BadSheet={BadSheet}, Identifier={Identifier}, MySection={MySection}, MySection_2={MySection_2}, BadAssets={BadAssets} }}";

        public static CodedConfig Load(Dictionary<string, DataTable> tables)
        {
            var cfg = new CodedConfig();
            if (tables.TryGetValue("2024-Q1", out var t__2024Q1)) cfg._2024Q1 = _2024Q1Config.FromDataTable(t__2024Q1);
            if (tables.TryGetValue("Bad Sheet!", out var t_BadSheet)) cfg.BadSheet = BadSheetConfig.FromDataTable(t_BadSheet);
            if (tables.TryGetValue("!!!", out var t_Identifier)) cfg.Identifier = IdentifierConfig.FromDataTable(t_Identifier);
            if (tables.TryGetValue("my-section", out var t_MySection)) cfg.MySection = MySectionConfig.FromDataTable(t_MySection);
            if (tables.TryGetValue("My Section", out var t_MySection_2)) cfg.MySection_2 = MySection_2Config.FromDataTable(t_MySection_2);
            // "Bad Assets!": asset values are fetched from Orchestrator via GetRobotAsset in the generated XAML snippet — not loaded from DataTable.
            return cfg;
        }
    }

    public class _2024Q1Config
    {
        /// <summary>Max items per quarter.</summary>
        public int MaxItems { get; set; } = 10;
        /// <summary>Prefix for log messages.</summary>
        public string LogPrefix { get; set; } = "Q1";

        public static _2024Q1Config FromDataTable(DataTable dt)
        {
            var cfg = new _2024Q1Config();
            foreach (DataRow row in dt.Rows)
            {
                if (row.ItemArray.Length < 2) continue;
                var key   = row[0]?.ToString()?.Trim();
                var value = row[1]?.ToString()?.Trim() ?? "";
                switch (key)
                {
                    case "MaxItems":
                        if (int.TryParse(value, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out var v_MaxItems)) cfg.MaxItems = v_MaxItems;
                        break;
                    case "LogPrefix": cfg.LogPrefix = value; break;
                }
            }
            return cfg;
        }

        public override string ToString() =>
            $"_2024Q1Config {{ MaxItems={MaxItems}, LogPrefix={LogPrefix} }}";
    }

    public class BadSheetConfig
    {
        /// <summary>First feature toggle.</summary>
        public string Feature_1 { get; set; } = "on";
        /// <summary>Contact email.</summary>
        public string UserEmail { get; set; } = "";
        /// <summary>Collides with user.email after PascalCase.</summary>
        public string UserEmail_2 { get; set; } = "";

        public static BadSheetConfig FromDataTable(DataTable dt)
        {
            var cfg = new BadSheetConfig();
            foreach (DataRow row in dt.Rows)
            {
                if (row.ItemArray.Length < 2) continue;
                var key   = row[0]?.ToString()?.Trim();
                var value = row[1]?.ToString()?.Trim() ?? "";
                switch (key)
                {
                    case "Feature#1": cfg.Feature_1 = value; break;
                    case "user.email": cfg.UserEmail = value; break;
                    case "user-email": cfg.UserEmail_2 = value; break;
                }
            }
            return cfg;
        }

        public override string ToString() =>
            $"BadSheetConfig {{ Feature_1={Feature_1}, UserEmail={UserEmail}, UserEmail_2={UserEmail_2} }}";
    }

    public class IdentifierConfig
    {
        /// <summary>Survives despite degenerate sheet name.</summary>
        public string Note { get; set; } = "placeholder";

        public static IdentifierConfig FromDataTable(DataTable dt)
        {
            var cfg = new IdentifierConfig();
            foreach (DataRow row in dt.Rows)
            {
                if (row.ItemArray.Length < 2) continue;
                var key   = row[0]?.ToString()?.Trim();
                var value = row[1]?.ToString()?.Trim() ?? "";
                switch (key)
                {
                    case "Note": cfg.Note = value; break;
                }
            }
            return cfg;
        }

        public override string ToString() =>
            $"IdentifierConfig {{ Note={Note} }}";
    }

    public class MySectionConfig
    {
        public string A { get; set; } = "1";

        public static MySectionConfig FromDataTable(DataTable dt)
        {
            var cfg = new MySectionConfig();
            foreach (DataRow row in dt.Rows)
            {
                if (row.ItemArray.Length < 2) continue;
                var key   = row[0]?.ToString()?.Trim();
                var value = row[1]?.ToString()?.Trim() ?? "";
                switch (key)
                {
                    case "A": cfg.A = value; break;
                }
            }
            return cfg;
        }

        public override string ToString() =>
            $"MySectionConfig {{ A={A} }}";
    }

    public class MySection_2Config
    {
        public string B { get; set; } = "2";

        public static MySection_2Config FromDataTable(DataTable dt)
        {
            var cfg = new MySection_2Config();
            foreach (DataRow row in dt.Rows)
            {
                if (row.ItemArray.Length < 2) continue;
                var key   = row[0]?.ToString()?.Trim();
                var value = row[1]?.ToString()?.Trim() ?? "";
                switch (key)
                {
                    case "B": cfg.B = value; break;
                }
            }
            return cfg;
        }

        public override string ToString() =>
            $"MySection_2Config {{ B={B} }}";
    }

    public class BadAssetsConfig
    {
        /// <summary>SAP credential.</summary>
        public string UserCred { get; set; } = "";
        /// <summary>Queue name asset.</summary>
        public string Queue_name { get; set; } = "";

        public override string ToString() =>
            $"BadAssetsConfig {{ UserCred={UserCred}, Queue_name={Queue_name} }}";
    }
}