// <auto-generated>
//     Generated by ConFigTree 0.2.0
//     https://rpapub.github.io/ConFigTree/
// </auto-generated>

#nullable enable

using System;
using System.Data;
using System.Collections.Generic;

namespace Cpmf.Config
{
    /// <summary>Root configuration object.</summary>
    public class CodedConfig
    {
        public SAPConfig SAP { get; set; } = new();
        public override string ToString() =>
            $"CodedConfig {{ SAP={SAP} }}";

        public static CodedConfig Load(Dictionary<string, DataTable> tables)
        {
            var cfg = new CodedConfig();
            if (tables.TryGetValue("SAP", out var t_SAP)) cfg.SAP = SAPConfig.FromDataTable(t_SAP);
            return cfg;
        }
    }

    public class SAPConfig
    {
        /// <summary>Expected sbar/pane[1] value. Empty = skip assertion.</summary>
        public string ExpectedSid { get; set; } = "";
        /// <summary>3-4 char SAP system ID.</summary>
        public string SystemId { get; set; } = "S01";
        /// <summary>SAP login language code.</summary>
        public string Language { get; set; } = "DE";

        public static SAPConfig FromDataTable(DataTable dt)
        {
            var cfg = new SAPConfig();
            foreach (DataRow row in dt.Rows)
            {
                if (row.ItemArray.Length < 2) continue;
                var key   = row[0]?.ToString()?.Trim();
                var value = row[1]?.ToString()?.Trim() ?? "";
                switch (key)
                {
                    case "ExpectedSid": cfg.ExpectedSid = value; break;
                    case "SystemId": cfg.SystemId = value; break;
                    case "Language": cfg.Language = value; break;
                }
            }
            return cfg;
        }

        public Cpmf.Config.CodedSapConfig ToCodedSapConfig() =>
            new Cpmf.Config.CodedSapConfig
            {
                SapLib = new Cpmf.Config.SapLibConfig
                {
                    ExpectedSid = ExpectedSid,
                    SystemId = string.IsNullOrEmpty(SystemId) ? "S01" : SystemId,
                    Language = string.IsNullOrEmpty(Language) ? "DE" : Language,
                }
            };

        public override string ToString() =>
            $"SAPConfig {{ ExpectedSid={ExpectedSid}, SystemId={SystemId}, Language={Language} }}";
    }
}