// <auto-generated>
//     Generated by ConFigTree 0.2.0
//     https://rpapub.github.io/ConFigTree/
// </auto-generated>

#nullable enable

using System;
using System.Data;
using System.Collections.Generic;

namespace Cpmf.Config
{
    /// <summary>Root configuration object.</summary>
    public class CodedConfig
    {
        public SettingsConfig Settings { get; set; } = new();
        public ConstantsConfig Constants { get; set; } = new();
        public EnvironmentsConfig Environments { get; set; } = new();
        public FeaturesConfig Features { get; set; } = new();
        public AssetsConfig Assets { get; set; } = new();
        public ConnectionsConfig Connections { get; set; } = new();
        public override string ToString() =>
            $"CodedConfig {{ Settings={Settings}, Constants={Constants}, Environments={Environments}, Features={Features}, Assets={Assets}, Connections={Connections} }}";

        public static CodedConfig Load(Dictionary<string, DataTable> tables)
        {
            var cfg = new CodedConfig();
            if (tables.TryGetValue("Settings", out var t_Settings)) cfg.Settings = SettingsConfig.FromDataTable(t_Settings);
            if (tables.TryGetValue("Constants", out var t_Constants)) cfg.Constants = ConstantsConfig.FromDataTable(t_Constants);
            if (tables.TryGetValue("Environments", out var t_Environments)) cfg.Environments = EnvironmentsConfig.FromDataTable(t_Environments);
            if (tables.TryGetValue("Features", out var t_Features)) cfg.Features = FeaturesConfig.FromDataTable(t_Features);
            // "Assets", "Connections": asset values are fetched from Orchestrator via GetRobotAsset in the generated XAML snippet — not loaded from DataTable.
            return cfg;
        }
    }

    public class SettingsConfig
    {
        /// <summary>string — Orchestrator input queue name.</summary>
        public string OrchestratorQueueName { get; set; } = "everything_input_queue";
        /// <summary>int — Maximum items to process per run.</summary>
        public int MaxItemsPerRun { get; set; } = 100;
        /// <summary>double — Processing threshold.</summary>
        public double Threshold { get; set; } = 3.14;
        /// <summary>double forced via DataType (cell is int).</summary>
        public double SampleRate { get; set; } = 4.0;
        /// <summary>bool — Master feature toggle.</summary>
        public bool IsEnabled { get; set; } = true;
        /// <summary>DateOnly — Last valid processing date.</summary>
        public DateOnly CutoffDate { get; set; } = new DateOnly(2025, 12, 31);
        /// <summary>DateTime — Next scheduled run.</summary>
        public DateTime ScheduledAt { get; set; } = new DateTime(2025, 6, 15, 9, 30, 0);
        /// <summary>TimeOnly — Daily start time.</summary>
        public TimeOnly DailyRunTime { get; set; } = new TimeOnly(8, 0, 0);

        public static SettingsConfig FromDataTable(DataTable dt)
        {
            var cfg = new SettingsConfig();
            foreach (DataRow row in dt.Rows)
            {
                if (row.ItemArray.Length < 2) continue;
                var key   = row[0]?.ToString()?.Trim();
                var value = row[1]?.ToString()?.Trim() ?? "";
                switch (key)
                {
                    case "OrchestratorQueueName": cfg.OrchestratorQueueName = value; break;
                    case "MaxItemsPerRun":
                        if (int.TryParse(value, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out var v_MaxItemsPerRun)) cfg.MaxItemsPerRun = v_MaxItemsPerRun;
                        break;
                    case "Threshold":
                        if (double.TryParse(value, System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, out var v_Threshold)) cfg.Threshold = v_Threshold;
                        break;
                    case "SampleRate":
                        if (double.TryParse(value, System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, out var v_SampleRate)) cfg.SampleRate = v_SampleRate;
                        break;
                    case "IsEnabled":
                        if (bool.TryParse(value, out var v_IsEnabled)) cfg.IsEnabled = v_IsEnabled;
                        break;
                    case "CutoffDate":
                        if (DateOnly.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var v_CutoffDate)) cfg.CutoffDate = v_CutoffDate;
                        else if (DateTime.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var dt_CutoffDate)) cfg.CutoffDate = DateOnly.FromDateTime(dt_CutoffDate);
                        break;
                    case "ScheduledAt":
                        if (DateTime.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var v_ScheduledAt)) cfg.ScheduledAt = v_ScheduledAt;
                        break;
                    case "DailyRunTime":
                        if (TimeOnly.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var v_DailyRunTime)) cfg.DailyRunTime = v_DailyRunTime;
                        else if (DateTime.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var dt_DailyRunTime)) cfg.DailyRunTime = TimeOnly.FromDateTime(dt_DailyRunTime);
                        break;
                }
            }
            return cfg;
        }

        public override string ToString() =>
            $"SettingsConfig {{ OrchestratorQueueName={OrchestratorQueueName}, MaxItemsPerRun={MaxItemsPerRun}, Threshold={Threshold}, SampleRate={SampleRate}, IsEnabled={IsEnabled}, CutoffDate={CutoffDate}, ScheduledAt={ScheduledAt}, DailyRunTime={DailyRunTime} }}";
    }

    public class ConstantsConfig
    {
        /// <summary>int — Must be 0 when using Orchestrator queues.</summary>
        public int MaxRetryNumber { get; set; } = 0;
        /// <summary>int — Stop job after this many consecutive errors.</summary>
        public int MaxConsecutiveSystemExceptions { get; set; } = 3;
        /// <summary>double — Mathematical constant.</summary>
        public double Pi { get; set; } = 3.14159;
        /// <summary>bool — Disable for permissive validation.</summary>
        public bool StrictMode { get; set; } = false;
        /// <summary>DateOnly — Config expiry date.</summary>
        public DateOnly ExpiresOn { get; set; } = new DateOnly(2026, 1, 1);
        /// <summary>DateTime — Config creation timestamp.</summary>
        public DateTime CreatedAt { get; set; } = new DateTime(2024, 3, 1, 12, 0, 0);
        /// <summary>TimeOnly — Processing window start.</summary>
        public TimeOnly WindowOpen { get; set; } = new TimeOnly(9, 0, 0);
        /// <summary>TimeOnly — Processing window end.</summary>
        public TimeOnly WindowClose { get; set; } = new TimeOnly(17, 30, 0);

        public static ConstantsConfig FromDataTable(DataTable dt)
        {
            var cfg = new ConstantsConfig();
            foreach (DataRow row in dt.Rows)
            {
                if (row.ItemArray.Length < 2) continue;
                var key   = row[0]?.ToString()?.Trim();
                var value = row[1]?.ToString()?.Trim() ?? "";
                switch (key)
                {
                    case "MaxRetryNumber":
                        if (int.TryParse(value, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out var v_MaxRetryNumber)) cfg.MaxRetryNumber = v_MaxRetryNumber;
                        break;
                    case "MaxConsecutiveSystemExceptions":
                        if (int.TryParse(value, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out var v_MaxConsecutiveSystemExceptions)) cfg.MaxConsecutiveSystemExceptions = v_MaxConsecutiveSystemExceptions;
                        break;
                    case "Pi":
                        if (double.TryParse(value, System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, out var v_Pi)) cfg.Pi = v_Pi;
                        break;
                    case "StrictMode":
                        if (bool.TryParse(value, out var v_StrictMode)) cfg.StrictMode = v_StrictMode;
                        break;
                    case "ExpiresOn":
                        if (DateOnly.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var v_ExpiresOn)) cfg.ExpiresOn = v_ExpiresOn;
                        else if (DateTime.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var dt_ExpiresOn)) cfg.ExpiresOn = DateOnly.FromDateTime(dt_ExpiresOn);
                        break;
                    case "CreatedAt":
                        if (DateTime.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var v_CreatedAt)) cfg.CreatedAt = v_CreatedAt;
                        break;
                    case "WindowOpen":
                        if (TimeOnly.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var v_WindowOpen)) cfg.WindowOpen = v_WindowOpen;
                        else if (DateTime.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var dt_WindowOpen)) cfg.WindowOpen = TimeOnly.FromDateTime(dt_WindowOpen);
                        break;
                    case "WindowClose":
                        if (TimeOnly.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var v_WindowClose)) cfg.WindowClose = v_WindowClose;
                        else if (DateTime.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var dt_WindowClose)) cfg.WindowClose = TimeOnly.FromDateTime(dt_WindowClose);
                        break;
                }
            }
            return cfg;
        }

        public override string ToString() =>
            $"ConstantsConfig {{ MaxRetryNumber={MaxRetryNumber}, MaxConsecutiveSystemExceptions={MaxConsecutiveSystemExceptions}, Pi={Pi}, StrictMode={StrictMode}, ExpiresOn={ExpiresOn}, CreatedAt={CreatedAt}, WindowOpen={WindowOpen}, WindowClose={WindowClose} }}";
    }

    public class EnvironmentsConfig
    {
        /// <summary>string — REST API base URL.</summary>
        public string BaseUrl { get; set; } = "https://uat.example.com";
        /// <summary>string — Deployment environment name.</summary>
        public string Environment { get; set; } = "UAT";
        /// <summary>int — HTTP request timeout in seconds.</summary>
        public int Timeout { get; set; } = 30;
        /// <summary>double — Delay between retries in seconds.</summary>
        public double RetryDelay { get; set; } = 2.5;

        public static EnvironmentsConfig FromDataTable(DataTable dt)
        {
            var cfg = new EnvironmentsConfig();
            foreach (DataRow row in dt.Rows)
            {
                if (row.ItemArray.Length < 2) continue;
                var key   = row[0]?.ToString()?.Trim();
                var value = row[1]?.ToString()?.Trim() ?? "";
                switch (key)
                {
                    case "BaseUrl": cfg.BaseUrl = value; break;
                    case "Environment": cfg.Environment = value; break;
                    case "Timeout":
                        if (int.TryParse(value, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out var v_Timeout)) cfg.Timeout = v_Timeout;
                        break;
                    case "RetryDelay":
                        if (double.TryParse(value, System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, out var v_RetryDelay)) cfg.RetryDelay = v_RetryDelay;
                        break;
                }
            }
            return cfg;
        }

        public override string ToString() =>
            $"EnvironmentsConfig {{ BaseUrl={BaseUrl}, Environment={Environment}, Timeout={Timeout}, RetryDelay={RetryDelay} }}";
    }

    public class FeaturesConfig
    {
        /// <summary>bool — Send email on job completion.</summary>
        public bool EnableNotifications { get; set; } = true;
        /// <summary>bool — Skip writes when true.</summary>
        public bool EnableDryRun { get; set; } = false;
        /// <summary>int — Parallel job slot limit.</summary>
        public int MaxParallelJobs { get; set; } = 4;
        /// <summary>string — Deployment stage label.</summary>
        public string FeatureLabel { get; set; } = "beta";

        public static FeaturesConfig FromDataTable(DataTable dt)
        {
            var cfg = new FeaturesConfig();
            foreach (DataRow row in dt.Rows)
            {
                if (row.ItemArray.Length < 2) continue;
                var key   = row[0]?.ToString()?.Trim();
                var value = row[1]?.ToString()?.Trim() ?? "";
                switch (key)
                {
                    case "EnableNotifications":
                        if (bool.TryParse(value, out var v_EnableNotifications)) cfg.EnableNotifications = v_EnableNotifications;
                        break;
                    case "EnableDryRun":
                        if (bool.TryParse(value, out var v_EnableDryRun)) cfg.EnableDryRun = v_EnableDryRun;
                        break;
                    case "MaxParallelJobs":
                        if (int.TryParse(value, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out var v_MaxParallelJobs)) cfg.MaxParallelJobs = v_MaxParallelJobs;
                        break;
                    case "FeatureLabel": cfg.FeatureLabel = value; break;
                }
            }
            return cfg;
        }

        public override string ToString() =>
            $"FeaturesConfig {{ EnableNotifications={EnableNotifications}, EnableDryRun={EnableDryRun}, MaxParallelJobs={MaxParallelJobs}, FeatureLabel={FeatureLabel} }}";
    }

    public class AssetsConfig
    {
        /// <summary>Input queue name.</summary>
        public string QueueName { get; set; } = "";
        /// <summary>Maximum items to process.</summary>
        public int MaxItemsPerRun { get; set; }
        /// <summary>Strict processing toggle.</summary>
        public bool StrictMode { get; set; }
        /// <summary>Untyped fallback asset.</summary>
        public object? GenericValue { get; set; }

        public override string ToString() =>
            $"AssetsConfig {{ QueueName={QueueName}, MaxItemsPerRun={MaxItemsPerRun}, StrictMode={StrictMode}, GenericValue={GenericValue} }}";
    }

    public class ConnectionsConfig
    {
        /// <summary>REST API endpoint URL.</summary>
        public string ApiEndpoint { get; set; } = "";
        /// <summary>Service base URL.</summary>
        public string BaseUrl { get; set; } = "";
        /// <summary>Orchestrator folder path.</summary>
        public string OrchestratorFolder { get; set; } = "";

        public override string ToString() =>
            $"ConnectionsConfig {{ ApiEndpoint={ApiEndpoint}, BaseUrl={BaseUrl}, OrchestratorFolder={OrchestratorFolder} }}";
    }
}