// <auto-generated>
//     Generated by ConFigTree 0.2.0
//     https://rpapub.github.io/ConFigTree/
// </auto-generated>

#nullable enable

using System;
using System.Data;
using System.Collections.Generic;

namespace Cpmf.Config
{
    /// <summary>Root configuration object.</summary>
    public class CodedConfig
    {
        public SettingsConfig Settings { get; set; } = new();
        public ConstantsConfig Constants { get; set; } = new();
        public AssetsConfig Assets { get; set; } = new();
        public override string ToString() =>
            $"CodedConfig {{ Settings={Settings}, Constants={Constants}, Assets={Assets} }}";

        public static CodedConfig Load(Dictionary<string, DataTable> tables)
        {
            var cfg = new CodedConfig();
            if (tables.TryGetValue("Settings", out var t_Settings)) cfg.Settings = SettingsConfig.FromDataTable(t_Settings);
            if (tables.TryGetValue("Constants", out var t_Constants)) cfg.Constants = ConstantsConfig.FromDataTable(t_Constants);
            // "Assets": asset values are fetched from Orchestrator via GetRobotAsset in the generated XAML snippet — not loaded from DataTable.
            return cfg;
        }
    }

    public class SettingsConfig
    {
        /// <summary>string</summary>
        public string FeatureName { get; set; } = "TypesDemo";
        /// <summary>int</summary>
        public int MaxItems { get; set; } = 42;
        /// <summary>double</summary>
        public double Threshold { get; set; } = 3.14;
        /// <summary>bool</summary>
        public bool IsEnabled { get; set; } = true;
        /// <summary>DateOnly — date only, time is 00:00:00</summary>
        public DateOnly CutoffDate { get; set; } = new DateOnly(2025, 12, 31);
        /// <summary>DateTime — has time component</summary>
        public DateTime ScheduledAt { get; set; } = new DateTime(2025, 6, 15, 9, 30, 0);
        /// <summary>TimeOnly — time only, no date</summary>
        public TimeOnly DailyRunTime { get; set; } = new TimeOnly(8, 0, 0);

        public static SettingsConfig FromDataTable(DataTable dt)
        {
            var cfg = new SettingsConfig();
            foreach (DataRow row in dt.Rows)
            {
                if (row.ItemArray.Length < 2) continue;
                var key   = row[0]?.ToString()?.Trim();
                var value = row[1]?.ToString()?.Trim() ?? "";
                switch (key)
                {
                    case "FeatureName": cfg.FeatureName = value; break;
                    case "MaxItems":
                        if (int.TryParse(value, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out var v_MaxItems)) cfg.MaxItems = v_MaxItems;
                        break;
                    case "Threshold":
                        if (double.TryParse(value, System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, out var v_Threshold)) cfg.Threshold = v_Threshold;
                        break;
                    case "IsEnabled":
                        if (bool.TryParse(value, out var v_IsEnabled)) cfg.IsEnabled = v_IsEnabled;
                        break;
                    case "CutoffDate":
                        if (DateOnly.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var v_CutoffDate)) cfg.CutoffDate = v_CutoffDate;
                        else if (DateTime.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var dt_CutoffDate)) cfg.CutoffDate = DateOnly.FromDateTime(dt_CutoffDate);
                        break;
                    case "ScheduledAt":
                        if (DateTime.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var v_ScheduledAt)) cfg.ScheduledAt = v_ScheduledAt;
                        break;
                    case "DailyRunTime":
                        if (TimeOnly.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var v_DailyRunTime)) cfg.DailyRunTime = v_DailyRunTime;
                        else if (DateTime.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var dt_DailyRunTime)) cfg.DailyRunTime = TimeOnly.FromDateTime(dt_DailyRunTime);
                        break;
                }
            }
            return cfg;
        }

        public override string ToString() =>
            $"SettingsConfig {{ FeatureName={FeatureName}, MaxItems={MaxItems}, Threshold={Threshold}, IsEnabled={IsEnabled}, CutoffDate={CutoffDate}, ScheduledAt={ScheduledAt}, DailyRunTime={DailyRunTime} }}";
    }

    public class ConstantsConfig
    {
        /// <summary>double — mathematical constant</summary>
        public double Pi { get; set; } = 3.14159;
        /// <summary>int</summary>
        public int MaxRetryNumber { get; set; } = 0;
        /// <summary>bool</summary>
        public bool StrictMode { get; set; } = false;
        /// <summary>DateOnly</summary>
        public DateOnly ExpiresOn { get; set; } = new DateOnly(2026, 1, 1);
        /// <summary>DateTime</summary>
        public DateTime CreatedAt { get; set; } = new DateTime(2024, 3, 1, 12, 0, 0);
        /// <summary>TimeOnly</summary>
        public TimeOnly WindowOpen { get; set; } = new TimeOnly(9, 0, 0);
        /// <summary>TimeOnly</summary>
        public TimeOnly WindowClose { get; set; } = new TimeOnly(17, 30, 0);

        public static ConstantsConfig FromDataTable(DataTable dt)
        {
            var cfg = new ConstantsConfig();
            foreach (DataRow row in dt.Rows)
            {
                if (row.ItemArray.Length < 2) continue;
                var key   = row[0]?.ToString()?.Trim();
                var value = row[1]?.ToString()?.Trim() ?? "";
                switch (key)
                {
                    case "Pi":
                        if (double.TryParse(value, System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, out var v_Pi)) cfg.Pi = v_Pi;
                        break;
                    case "MaxRetryNumber":
                        if (int.TryParse(value, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out var v_MaxRetryNumber)) cfg.MaxRetryNumber = v_MaxRetryNumber;
                        break;
                    case "StrictMode":
                        if (bool.TryParse(value, out var v_StrictMode)) cfg.StrictMode = v_StrictMode;
                        break;
                    case "ExpiresOn":
                        if (DateOnly.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var v_ExpiresOn)) cfg.ExpiresOn = v_ExpiresOn;
                        else if (DateTime.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var dt_ExpiresOn)) cfg.ExpiresOn = DateOnly.FromDateTime(dt_ExpiresOn);
                        break;
                    case "CreatedAt":
                        if (DateTime.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var v_CreatedAt)) cfg.CreatedAt = v_CreatedAt;
                        break;
                    case "WindowOpen":
                        if (TimeOnly.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var v_WindowOpen)) cfg.WindowOpen = v_WindowOpen;
                        else if (DateTime.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var dt_WindowOpen)) cfg.WindowOpen = TimeOnly.FromDateTime(dt_WindowOpen);
                        break;
                    case "WindowClose":
                        if (TimeOnly.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var v_WindowClose)) cfg.WindowClose = v_WindowClose;
                        else if (DateTime.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var dt_WindowClose)) cfg.WindowClose = TimeOnly.FromDateTime(dt_WindowClose);
                        break;
                }
            }
            return cfg;
        }

        public override string ToString() =>
            $"ConstantsConfig {{ Pi={Pi}, MaxRetryNumber={MaxRetryNumber}, StrictMode={StrictMode}, ExpiresOn={ExpiresOn}, CreatedAt={CreatedAt}, WindowOpen={WindowOpen}, WindowClose={WindowClose} }}";
    }

    public class AssetsConfig
    {
        // No data rows found in source sheet.
    }
}