// <auto-generated>
//     Generated by ConFigTree 0.2.0
//     https://rpapub.github.io/ConFigTree/
// </auto-generated>

#nullable enable

using System;
using System.Data;
using System.Collections.Generic;

namespace Cpmf.Config
{
    /// <summary>Root configuration object.</summary>
    public class CodedConfig
    {
        public SettingsConfig Settings { get; set; } = new();
        public ConstantsConfig Constants { get; set; } = new();
        public AssetsConfig Assets { get; set; } = new();
        public EnvironmentsConfig Environments { get; set; } = new();
        public FeaturesConfig Features { get; set; } = new();
        public override string ToString() =>
            $"CodedConfig {{ Settings={Settings}, Constants={Constants}, Assets={Assets}, Environments={Environments}, Features={Features} }}";

        public static CodedConfig Load(Dictionary<string, DataTable> tables)
        {
            var cfg = new CodedConfig();
            if (tables.TryGetValue("Settings", out var t_Settings)) cfg.Settings = SettingsConfig.FromDataTable(t_Settings);
            if (tables.TryGetValue("Constants", out var t_Constants)) cfg.Constants = ConstantsConfig.FromDataTable(t_Constants);
            if (tables.TryGetValue("Environments", out var t_Environments)) cfg.Environments = EnvironmentsConfig.FromDataTable(t_Environments);
            if (tables.TryGetValue("Features", out var t_Features)) cfg.Features = FeaturesConfig.FromDataTable(t_Features);
            // "Assets": asset values are fetched from Orchestrator via GetRobotAsset in the generated XAML snippet — not loaded from DataTable.
            return cfg;
        }
    }

    public class SettingsConfig
    {
        /// <summary>Orchestrator queue name.</summary>
        public string OrchestratorQueueName { get; set; } = "MultiQueue";
        /// <summary>Max items per run.</summary>
        public int MaxItemsPerRun { get; set; } = 50;

        public static SettingsConfig FromDataTable(DataTable dt)
        {
            var cfg = new SettingsConfig();
            foreach (DataRow row in dt.Rows)
            {
                if (row.ItemArray.Length < 2) continue;
                var key   = row[0]?.ToString()?.Trim();
                var value = row[1]?.ToString()?.Trim() ?? "";
                switch (key)
                {
                    case "OrchestratorQueueName": cfg.OrchestratorQueueName = value; break;
                    case "MaxItemsPerRun":
                        if (int.TryParse(value, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out var v_MaxItemsPerRun)) cfg.MaxItemsPerRun = v_MaxItemsPerRun;
                        break;
                }
            }
            return cfg;
        }

        public override string ToString() =>
            $"SettingsConfig {{ OrchestratorQueueName={OrchestratorQueueName}, MaxItemsPerRun={MaxItemsPerRun} }}";
    }

    public class ConstantsConfig
    {
        /// <summary>Must be 0 when using Orchestrator queues.</summary>
        public int MaxRetryNumber { get; set; } = 0;

        public static ConstantsConfig FromDataTable(DataTable dt)
        {
            var cfg = new ConstantsConfig();
            foreach (DataRow row in dt.Rows)
            {
                if (row.ItemArray.Length < 2) continue;
                var key   = row[0]?.ToString()?.Trim();
                var value = row[1]?.ToString()?.Trim() ?? "";
                switch (key)
                {
                    case "MaxRetryNumber":
                        if (int.TryParse(value, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out var v_MaxRetryNumber)) cfg.MaxRetryNumber = v_MaxRetryNumber;
                        break;
                }
            }
            return cfg;
        }

        public override string ToString() =>
            $"ConstantsConfig {{ MaxRetryNumber={MaxRetryNumber} }}";
    }

    public class AssetsConfig
    {
        /// <summary>SAP credential.</summary>
        public object? CredentialSap { get; set; }

        public override string ToString() =>
            $"AssetsConfig {{ CredentialSap={CredentialSap} }}";
    }

    public class EnvironmentsConfig
    {
        /// <summary>API base URL.</summary>
        public string BaseUrl { get; set; } = "https://uat.example.com";
        /// <summary>Deployment environment.</summary>
        public string Environment { get; set; } = "UAT";
        /// <summary>HTTP timeout in seconds.</summary>
        public int Timeout { get; set; } = 30;

        public static EnvironmentsConfig FromDataTable(DataTable dt)
        {
            var cfg = new EnvironmentsConfig();
            foreach (DataRow row in dt.Rows)
            {
                if (row.ItemArray.Length < 2) continue;
                var key   = row[0]?.ToString()?.Trim();
                var value = row[1]?.ToString()?.Trim() ?? "";
                switch (key)
                {
                    case "BaseUrl": cfg.BaseUrl = value; break;
                    case "Environment": cfg.Environment = value; break;
                    case "Timeout":
                        if (int.TryParse(value, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out var v_Timeout)) cfg.Timeout = v_Timeout;
                        break;
                }
            }
            return cfg;
        }

        public override string ToString() =>
            $"EnvironmentsConfig {{ BaseUrl={BaseUrl}, Environment={Environment}, Timeout={Timeout} }}";
    }

    public class FeaturesConfig
    {
        /// <summary>Send email notifications on completion.</summary>
        public bool EnableNotifications { get; set; } = true;
        /// <summary>Skip writes when true.</summary>
        public bool EnableDryRun { get; set; } = false;
        /// <summary>Number of parallel job slots.</summary>
        public int MaxParallelJobs { get; set; } = 4;

        public static FeaturesConfig FromDataTable(DataTable dt)
        {
            var cfg = new FeaturesConfig();
            foreach (DataRow row in dt.Rows)
            {
                if (row.ItemArray.Length < 2) continue;
                var key   = row[0]?.ToString()?.Trim();
                var value = row[1]?.ToString()?.Trim() ?? "";
                switch (key)
                {
                    case "EnableNotifications":
                        if (bool.TryParse(value, out var v_EnableNotifications)) cfg.EnableNotifications = v_EnableNotifications;
                        break;
                    case "EnableDryRun":
                        if (bool.TryParse(value, out var v_EnableDryRun)) cfg.EnableDryRun = v_EnableDryRun;
                        break;
                    case "MaxParallelJobs":
                        if (int.TryParse(value, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out var v_MaxParallelJobs)) cfg.MaxParallelJobs = v_MaxParallelJobs;
                        break;
                }
            }
            return cfg;
        }

        public override string ToString() =>
            $"FeaturesConfig {{ EnableNotifications={EnableNotifications}, EnableDryRun={EnableDryRun}, MaxParallelJobs={MaxParallelJobs} }}";
    }
}