// <auto-generated>
//     Generated by ConFigTree 0.2.0
//     https://rpapub.github.io/ConFigTree/
// </auto-generated>

#nullable enable

using System;
using System.Data;
using System.Collections.Generic;

namespace Cpmf.Config
{
    /// <summary>Root configuration object.</summary>
    public class CodedConfig
    {
        public OverridesConfig Overrides { get; set; } = new();
        public override string ToString() =>
            $"CodedConfig {{ Overrides={Overrides} }}";

        public static CodedConfig Load(Dictionary<string, DataTable> tables)
        {
            var cfg = new CodedConfig();
            if (tables.TryGetValue("Overrides", out var t_Overrides)) cfg.Overrides = OverridesConfig.FromDataTable(t_Overrides);
            return cfg;
        }
    }

    public class OverridesConfig
    {
        /// <summary>int cell forced to double.</summary>
        public double SampleRate { get; set; } = 4.0;
        /// <summary>int inferred (empty DataType).</summary>
        public int MaxRetries { get; set; } = 3;
        /// <summary>string inferred (bogus DataType).</summary>
        public string Label { get; set; } = "beta";
        /// <summary>Credential ref sentinel.</summary>
        public string CredentialSap { get; set; } = "";
        public string CredentialSapFolder => CredentialSap.Contains('/') ? CredentialSap.Split('/')[0] : "";
        public string CredentialSapName   => CredentialSap.Contains('/') ? CredentialSap.Split('/')[1] : CredentialSap;
        /// <summary>Asset ref sentinel.</summary>
        public string QueueRef { get; set; } = "";
        public string QueueRefFolder => QueueRef.Contains('/') ? QueueRef.Split('/')[0] : "";
        public string QueueRefName   => QueueRef.Contains('/') ? QueueRef.Split('/')[1] : QueueRef;

        public static OverridesConfig FromDataTable(DataTable dt)
        {
            var cfg = new OverridesConfig();
            foreach (DataRow row in dt.Rows)
            {
                if (row.ItemArray.Length < 2) continue;
                var key   = row[0]?.ToString()?.Trim();
                var value = row[1]?.ToString()?.Trim() ?? "";
                switch (key)
                {
                    case "SampleRate":
                        if (double.TryParse(value, System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, out var v_SampleRate)) cfg.SampleRate = v_SampleRate;
                        break;
                    case "MaxRetries":
                        if (int.TryParse(value, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out var v_MaxRetries)) cfg.MaxRetries = v_MaxRetries;
                        break;
                    case "Label": cfg.Label = value; break;
                    case "CredentialSap": cfg.CredentialSap = value; break;
                    case "QueueRef": cfg.QueueRef = value; break;
                }
            }
            return cfg;
        }

        public override string ToString() =>
            $"OverridesConfig {{ SampleRate={SampleRate}, MaxRetries={MaxRetries}, Label={Label}, CredentialSap={CredentialSap}, QueueRef={QueueRef} }}";
    }
}