// <auto-generated>
//     Generated by ConFigTree 0.2.0
//     https://rpapub.github.io/ConFigTree/
// </auto-generated>

#nullable enable

using System;
using System.Data;
using System.Collections.Generic;

namespace Cpmf.Config
{
    /// <summary>Root configuration object.</summary>
    public class CodedConfig
    {
        public DatabaseConfig Database { get; set; } = new();
        public SmtpConfig Smtp { get; set; } = new();
        public CredentialsConfig Credentials { get; set; } = new();
        public override string ToString() =>
            $"CodedConfig {{ Database={Database}, Smtp={Smtp}, Credentials={Credentials} }}";

        public static CodedConfig Load(Dictionary<string, DataTable> tables)
        {
            var cfg = new CodedConfig();
            if (tables.TryGetValue("Database", out var t_Database)) cfg.Database = DatabaseConfig.FromDataTable(t_Database);
            if (tables.TryGetValue("Smtp", out var t_Smtp)) cfg.Smtp = SmtpConfig.FromDataTable(t_Smtp);
            // "Credentials": asset values are fetched from Orchestrator via GetRobotAsset in the generated XAML snippet — not loaded from DataTable.
            return cfg;
        }
    }

    public class DatabaseConfig
    {
        /// <summary>ADO.NET connection string.</summary>
        public string ConnectionString { get; set; } = "Server=db;Database=app;";
        /// <summary>Query timeout in seconds.</summary>
        public int CommandTimeout { get; set; } = 30;
        /// <summary>Connection pool size.</summary>
        public int MaxPoolSize { get; set; } = 10;

        public static DatabaseConfig FromDataTable(DataTable dt)
        {
            var cfg = new DatabaseConfig();
            foreach (DataRow row in dt.Rows)
            {
                if (row.ItemArray.Length < 2) continue;
                var key   = row[0]?.ToString()?.Trim();
                var value = row[1]?.ToString()?.Trim() ?? "";
                switch (key)
                {
                    case "ConnectionString": cfg.ConnectionString = value; break;
                    case "CommandTimeout":
                        if (int.TryParse(value, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out var v_CommandTimeout)) cfg.CommandTimeout = v_CommandTimeout;
                        break;
                    case "MaxPoolSize":
                        if (int.TryParse(value, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out var v_MaxPoolSize)) cfg.MaxPoolSize = v_MaxPoolSize;
                        break;
                }
            }
            return cfg;
        }

        public override string ToString() =>
            $"DatabaseConfig {{ ConnectionString={ConnectionString}, CommandTimeout={CommandTimeout}, MaxPoolSize={MaxPoolSize} }}";
    }

    public class SmtpConfig
    {
        /// <summary>SMTP server hostname.</summary>
        public string Host { get; set; } = "smtp.example.com";
        /// <summary>SMTP port.</summary>
        public int Port { get; set; } = 587;
        /// <summary>Enable TLS.</summary>
        public bool UseSsl { get; set; } = true;
        /// <summary>Sender address.</summary>
        public string FromAddress { get; set; } = "bot@example.com";

        public static SmtpConfig FromDataTable(DataTable dt)
        {
            var cfg = new SmtpConfig();
            foreach (DataRow row in dt.Rows)
            {
                if (row.ItemArray.Length < 2) continue;
                var key   = row[0]?.ToString()?.Trim();
                var value = row[1]?.ToString()?.Trim() ?? "";
                switch (key)
                {
                    case "Host": cfg.Host = value; break;
                    case "Port":
                        if (int.TryParse(value, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out var v_Port)) cfg.Port = v_Port;
                        break;
                    case "UseSsl":
                        if (bool.TryParse(value, out var v_UseSsl)) cfg.UseSsl = v_UseSsl;
                        break;
                    case "FromAddress": cfg.FromAddress = value; break;
                }
            }
            return cfg;
        }

        public override string ToString() =>
            $"SmtpConfig {{ Host={Host}, Port={Port}, UseSsl={UseSsl}, FromAddress={FromAddress} }}";
    }

    public class CredentialsConfig
    {
        /// <summary>SMTP login credential.</summary>
        public object? SmtpCredential { get; set; }
        /// <summary>Database user password.</summary>
        public object? DatabasePassword { get; set; }

        public override string ToString() =>
            $"CredentialsConfig {{ SmtpCredential={SmtpCredential}, DatabasePassword={DatabasePassword} }}";
    }
}