// <auto-generated>
//     Generated by ConFigTree 0.2.0
//     https://rpapub.github.io/ConFigTree/
// </auto-generated>

#nullable enable

using System;
using System.Data;
using System.Collections.Generic;

namespace Cpmf.Config
{
    /// <summary>Root configuration object.</summary>
    public class CodedConfig
    {
        public SettingsConfig Settings { get; set; } = new();
        public ConstantsConfig Constants { get; set; } = new();
        public AssetsConfig Assets { get; set; } = new();
        public TargetsConfig Targets { get; set; } = new();
        public override string ToString() =>
            $"CodedConfig {{ Settings={Settings}, Constants={Constants}, Assets={Assets}, Targets={Targets} }}";

        public static CodedConfig Load(Dictionary<string, DataTable> tables)
        {
            var cfg = new CodedConfig();
            if (tables.TryGetValue("Settings", out var t_Settings)) cfg.Settings = SettingsConfig.FromDataTable(t_Settings);
            if (tables.TryGetValue("Constants", out var t_Constants)) cfg.Constants = ConstantsConfig.FromDataTable(t_Constants);
            if (tables.TryGetValue("Targets", out var t_Targets)) cfg.Targets = TargetsConfig.FromDataTable(t_Targets);
            // "Assets": asset values are fetched from Orchestrator via GetRobotAsset in the generated XAML snippet — not loaded from DataTable.
            return cfg;
        }
    }

    public class SettingsConfig
    {
        /// <summary>string</summary>
        public string FeatureName { get; init; } = "TypesDemo";
        /// <summary>int</summary>
        public int MaxItems { get; init; } = 42;
        /// <summary>double</summary>
        public double Threshold { get; init; } = 3.14;
        /// <summary>bool</summary>
        public bool IsEnabled { get; init; } = true;
        /// <summary>DateOnly — date only, time is 00:00:00</summary>
        public DateOnly CutoffDate { get; init; } = new DateOnly(2025, 12, 31);
        /// <summary>DateTime — has time component</summary>
        public DateTime ScheduledAt { get; init; } = new DateTime(2025, 6, 15, 9, 30, 0);
        /// <summary>TimeOnly — time only, no date</summary>
        public TimeOnly DailyRunTime { get; init; } = new TimeOnly(8, 0, 0);
        /// <summary>SAP Orchestrator credential.</summary>
        public string SapCredential { get; init; } = "";
        public string SapCredentialFolder => SapCredential.Contains('/') ? SapCredential.Split('/')[0] : "";
        public string SapCredentialName   => SapCredential.Contains('/') ? SapCredential.Split('/')[1] : SapCredential;
        /// <summary>Queue name Orchestrator asset.</summary>
        public string QueueNameRef { get; init; } = "";
        public string QueueNameRefFolder => QueueNameRef.Contains('/') ? QueueNameRef.Split('/')[0] : "";
        public string QueueNameRefName   => QueueNameRef.Contains('/') ? QueueNameRef.Split('/')[1] : QueueNameRef;

        public static SettingsConfig FromDataTable(DataTable dt)
        {
            string loc_FeatureName = "";
            int loc_MaxItems = 0;
            double loc_Threshold = 0.0;
            bool loc_IsEnabled = false;
            DateOnly loc_CutoffDate = default;
            DateTime loc_ScheduledAt = default;
            TimeOnly loc_DailyRunTime = default;
            string loc_SapCredential = "";
            string loc_QueueNameRef = "";
            foreach (DataRow row in dt.Rows)
            {
                if (row.ItemArray.Length < 2) continue;
                var key   = row[0]?.ToString()?.Trim();
                var value = row[1]?.ToString()?.Trim() ?? "";
                switch (key)
                {
                    case "FeatureName": loc_FeatureName = value; break;
                    case "MaxItems":
                        if (int.TryParse(value, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out var tmp_MaxItems)) loc_MaxItems = tmp_MaxItems;
                        break;
                    case "Threshold":
                        if (double.TryParse(value, System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, out var tmp_Threshold)) loc_Threshold = tmp_Threshold;
                        break;
                    case "IsEnabled":
                        if (bool.TryParse(value, out var tmp_IsEnabled)) loc_IsEnabled = tmp_IsEnabled;
                        break;
                    case "CutoffDate":
                        if (DateOnly.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var tmp_CutoffDate)) loc_CutoffDate = tmp_CutoffDate;
                        else if (DateTime.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var dt_CutoffDate)) loc_CutoffDate = DateOnly.FromDateTime(dt_CutoffDate);
                        break;
                    case "ScheduledAt":
                        if (DateTime.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var tmp_ScheduledAt)) loc_ScheduledAt = tmp_ScheduledAt;
                        break;
                    case "DailyRunTime":
                        if (TimeOnly.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var tmp_DailyRunTime)) loc_DailyRunTime = tmp_DailyRunTime;
                        else if (DateTime.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var dt_DailyRunTime)) loc_DailyRunTime = TimeOnly.FromDateTime(dt_DailyRunTime);
                        break;
                    case "SapCredential": loc_SapCredential = value; break;
                    case "QueueNameRef": loc_QueueNameRef = value; break;
                }
            }
            return new SettingsConfig
            {
                FeatureName = loc_FeatureName,
                MaxItems = loc_MaxItems,
                Threshold = loc_Threshold,
                IsEnabled = loc_IsEnabled,
                CutoffDate = loc_CutoffDate,
                ScheduledAt = loc_ScheduledAt,
                DailyRunTime = loc_DailyRunTime,
                SapCredential = loc_SapCredential,
                QueueNameRef = loc_QueueNameRef,
            };
        }

        public override string ToString() =>
            $"SettingsConfig {{ FeatureName={FeatureName}, MaxItems={MaxItems}, Threshold={Threshold}, IsEnabled={IsEnabled}, CutoffDate={CutoffDate}, ScheduledAt={ScheduledAt}, DailyRunTime={DailyRunTime}, SapCredential={SapCredential}, QueueNameRef={QueueNameRef} }}";
    }

    public class ConstantsConfig
    {
        /// <summary>double — mathematical constant</summary>
        public double Pi { get; init; } = 3.14159;
        /// <summary>int</summary>
        public int MaxRetryNumber { get; init; } = 0;
        /// <summary>bool</summary>
        public bool StrictMode { get; init; } = false;
        /// <summary>DateOnly</summary>
        public DateOnly ExpiresOn { get; init; } = new DateOnly(2026, 1, 1);
        /// <summary>DateTime</summary>
        public DateTime CreatedAt { get; init; } = new DateTime(2024, 3, 1, 12, 0, 0);
        /// <summary>TimeOnly</summary>
        public TimeOnly WindowOpen { get; init; } = new TimeOnly(9, 0, 0);
        /// <summary>TimeOnly</summary>
        public TimeOnly WindowClose { get; init; } = new TimeOnly(17, 30, 0);

        public static ConstantsConfig FromDataTable(DataTable dt)
        {
            double loc_Pi = 0.0;
            int loc_MaxRetryNumber = 0;
            bool loc_StrictMode = false;
            DateOnly loc_ExpiresOn = default;
            DateTime loc_CreatedAt = default;
            TimeOnly loc_WindowOpen = default;
            TimeOnly loc_WindowClose = default;
            foreach (DataRow row in dt.Rows)
            {
                if (row.ItemArray.Length < 2) continue;
                var key   = row[0]?.ToString()?.Trim();
                var value = row[1]?.ToString()?.Trim() ?? "";
                switch (key)
                {
                    case "Pi":
                        if (double.TryParse(value, System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, out var tmp_Pi)) loc_Pi = tmp_Pi;
                        break;
                    case "MaxRetryNumber":
                        if (int.TryParse(value, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out var tmp_MaxRetryNumber)) loc_MaxRetryNumber = tmp_MaxRetryNumber;
                        break;
                    case "StrictMode":
                        if (bool.TryParse(value, out var tmp_StrictMode)) loc_StrictMode = tmp_StrictMode;
                        break;
                    case "ExpiresOn":
                        if (DateOnly.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var tmp_ExpiresOn)) loc_ExpiresOn = tmp_ExpiresOn;
                        else if (DateTime.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var dt_ExpiresOn)) loc_ExpiresOn = DateOnly.FromDateTime(dt_ExpiresOn);
                        break;
                    case "CreatedAt":
                        if (DateTime.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var tmp_CreatedAt)) loc_CreatedAt = tmp_CreatedAt;
                        break;
                    case "WindowOpen":
                        if (TimeOnly.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var tmp_WindowOpen)) loc_WindowOpen = tmp_WindowOpen;
                        else if (DateTime.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var dt_WindowOpen)) loc_WindowOpen = TimeOnly.FromDateTime(dt_WindowOpen);
                        break;
                    case "WindowClose":
                        if (TimeOnly.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var tmp_WindowClose)) loc_WindowClose = tmp_WindowClose;
                        else if (DateTime.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var dt_WindowClose)) loc_WindowClose = TimeOnly.FromDateTime(dt_WindowClose);
                        break;
                }
            }
            return new ConstantsConfig
            {
                Pi = loc_Pi,
                MaxRetryNumber = loc_MaxRetryNumber,
                StrictMode = loc_StrictMode,
                ExpiresOn = loc_ExpiresOn,
                CreatedAt = loc_CreatedAt,
                WindowOpen = loc_WindowOpen,
                WindowClose = loc_WindowClose,
            };
        }

        public override string ToString() =>
            $"ConstantsConfig {{ Pi={Pi}, MaxRetryNumber={MaxRetryNumber}, StrictMode={StrictMode}, ExpiresOn={ExpiresOn}, CreatedAt={CreatedAt}, WindowOpen={WindowOpen}, WindowClose={WindowClose} }}";
    }

    public class AssetsConfig
    {
        /// <summary>M365 service credential.</summary>
        public object? CredentialM365 { get; init; }
        /// <summary>FTP server credential.</summary>
        public object? CredentialFtp { get; init; }
        /// <summary>Input queue name.</summary>
        public string QueueNameAsset { get; init; } = "";
        /// <summary>Max items to process.</summary>
        public int MaxItemsAsset { get; init; }
        /// <summary>Strict processing toggle.</summary>
        public bool StrictModeAsset { get; init; }

        public override string ToString() =>
            $"AssetsConfig {{ CredentialM365={CredentialM365}, CredentialFtp={CredentialFtp}, QueueNameAsset={QueueNameAsset}, MaxItemsAsset={MaxItemsAsset}, StrictModeAsset={StrictModeAsset} }}";
    }

    public class TargetsConfig
    {
        /// <summary>Target host address.</summary>
        public string Host { get; init; } = "targets.example.com";
        /// <summary>Target port number.</summary>
        public int Port { get; init; } = 8080;
        /// <summary>Enable target connection.</summary>
        public bool Enabled { get; init; } = true;

        public static TargetsConfig FromDataTable(DataTable dt)
        {
            string loc_Host = "";
            int loc_Port = 0;
            bool loc_Enabled = false;
            foreach (DataRow row in dt.Rows)
            {
                if (row.ItemArray.Length < 2) continue;
                var key   = row[0]?.ToString()?.Trim();
                var value = row[1]?.ToString()?.Trim() ?? "";
                switch (key)
                {
                    case "Host": loc_Host = value; break;
                    case "Port":
                        if (int.TryParse(value, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out var tmp_Port)) loc_Port = tmp_Port;
                        break;
                    case "Enabled":
                        if (bool.TryParse(value, out var tmp_Enabled)) loc_Enabled = tmp_Enabled;
                        break;
                }
            }
            return new TargetsConfig
            {
                Host = loc_Host,
                Port = loc_Port,
                Enabled = loc_Enabled,
            };
        }

        public Acme.External.TargetConfig ToTargetConfig() =>
            new Acme.External.TargetConfig
            {
                Host = string.IsNullOrEmpty(Host) ? "targets.example.com" : Host,
                Port = Port,
                Enabled = Enabled,
            };

        public override string ToString() =>
            $"TargetsConfig {{ Host={Host}, Port={Port}, Enabled={Enabled} }}";
    }
}