// <auto-generated>
//     Generated by ConFigTree 0.2.0
//     https://rpapub.github.io/ConFigTree/
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace Cpmf.Config
{
    /// <summary>Root configuration object.</summary>
    public class CodedConfig
    {
        public SettingsConfig Settings { get; set; } = new();
        public ConstantsConfig Constants { get; set; } = new();
        public AssetsConfig Assets { get; set; } = new();
        public TargetsConfig Targets { get; set; } = new();
        public override string ToString() =>
            $"CodedConfig {{ Settings={Settings}, Constants={Constants}, Assets={Assets}, Targets={Targets} }}";

        // Requires NuGet: Tomlyn
        public static CodedConfig LoadToml(string filePath)
        {
            var toml = System.IO.File.ReadAllText(filePath);
            return Tomlyn.TomlSerializer.Deserialize<CodedConfig>(toml);
        }
    }

    public class SettingsConfig
    {
        public string FeatureName { get; set; } = "";
        public int MaxItems { get; set; }
        public double Threshold { get; set; }
        public bool IsEnabled { get; set; }
        public DateOnly CutoffDate { get; set; }
        public DateTime ScheduledAt { get; set; }
        public TimeOnly DailyRunTime { get; set; }

        public override string ToString() =>
            $"SettingsConfig {{ FeatureName={FeatureName}, MaxItems={MaxItems}, Threshold={Threshold}, IsEnabled={IsEnabled}, CutoffDate={CutoffDate}, ScheduledAt={ScheduledAt}, DailyRunTime={DailyRunTime} }}";
    }

    public class ConstantsConfig
    {
        public double Pi { get; set; }
        public int MaxRetryNumber { get; set; }
        public bool StrictMode { get; set; }
        public DateOnly ExpiresOn { get; set; }
        public DateTime CreatedAt { get; set; }
        public TimeOnly WindowOpen { get; set; }
        public TimeOnly WindowClose { get; set; }

        public override string ToString() =>
            $"ConstantsConfig {{ Pi={Pi}, MaxRetryNumber={MaxRetryNumber}, StrictMode={StrictMode}, ExpiresOn={ExpiresOn}, CreatedAt={CreatedAt}, WindowOpen={WindowOpen}, WindowClose={WindowClose} }}";
    }

    public class AssetsConfig
    {
        /// <summary>M365 service credential.</summary>
        public object? CredentialM365 { get; set; }
        /// <summary>FTP server credential.</summary>
        public object? CredentialFtp { get; set; }
        /// <summary>Input queue name.</summary>
        public string QueueNameAsset { get; set; } = "";
        /// <summary>Max items to process.</summary>
        public int MaxItemsAsset { get; set; }
        /// <summary>Strict processing toggle.</summary>
        public bool StrictModeAsset { get; set; }

        public override string ToString() =>
            $"AssetsConfig {{ CredentialM365={CredentialM365}, CredentialFtp={CredentialFtp}, QueueNameAsset={QueueNameAsset}, MaxItemsAsset={MaxItemsAsset}, StrictModeAsset={StrictModeAsset} }}";
    }

    public class TargetsConfig
    {
        public string Host { get; set; } = "";
        public int Port { get; set; }
        public bool Enabled { get; set; }

        public Acme.External.TargetConfig ToTargetConfig() =>
            new Acme.External.TargetConfig
            {
                Host = string.IsNullOrEmpty(Host) ? "targets.example.com" : Host,
                Port = Port,
                Enabled = Enabled,
            };

        public override string ToString() =>
            $"TargetsConfig {{ Host={Host}, Port={Port}, Enabled={Enabled} }}";
    }
}