// <auto-generated>
//     Generated by ConFigTree 0.2.0
//     https://rpapub.github.io/ConFigTree/
// </auto-generated>

#nullable enable

using System;
using System.Data;
using System.Collections.Generic;

namespace Cpmf.Config
{
    /// <summary>Root configuration object.</summary>
    public class CodedConfig
    {
        public AssetsConfig Assets { get; set; } = new();
        public EndpointsConfig Endpoints { get; set; } = new();
        public override string ToString() =>
            $"CodedConfig {{ Assets={Assets}, Endpoints={Endpoints} }}";

        public static CodedConfig Load(Dictionary<string, DataTable> tables)
        {
            var cfg = new CodedConfig();
            // "Assets", "Endpoints": asset values are fetched from Orchestrator via GetRobotAsset in the generated XAML snippet — not loaded from DataTable.
            return cfg;
        }
    }

    public class AssetsConfig
    {
        /// <summary>Input queue name.</summary>
        public string QueueName { get; set; } = "";
        /// <summary>Max items to process.</summary>
        public int MaxItemsPerRun { get; set; }
        /// <summary>Enable strict processing.</summary>
        public bool StrictMode { get; set; }
        /// <summary>REST API base URL.</summary>
        public string ApiEndpoint { get; set; } = "";
        /// <summary>Untyped — no ValueType.</summary>
        public object? GenericValue { get; set; }

        public override string ToString() =>
            $"AssetsConfig {{ QueueName={QueueName}, MaxItemsPerRun={MaxItemsPerRun}, StrictMode={StrictMode}, ApiEndpoint={ApiEndpoint}, GenericValue={GenericValue} }}";
    }

    public class EndpointsConfig
    {
        /// <summary>REST API base URL.</summary>
        public object? BaseUrl { get; set; }
        /// <summary>Orchestrator folder path for queue operations.</summary>
        public object? OrchestratorFolder { get; set; }

        public override string ToString() =>
            $"EndpointsConfig {{ BaseUrl={BaseUrl}, OrchestratorFolder={OrchestratorFolder} }}";
    }
}