// <auto-generated>
//     Generated by ConFigTree 0.2.0
//     https://rpapub.github.io/ConFigTree/
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace Cpmf.Config
{
    /// <summary>Root configuration object.</summary>
    public class CodedConfig
    {
        public SettingsConfig Settings { get; set; } = new();
        public ConstantsConfig Constants { get; set; } = new();
        public AssetsConfig Assets { get; set; } = new();
        public override string ToString() =>
            $"CodedConfig {{ Settings={Settings}, Constants={Constants}, Assets={Assets} }}";

        // Requires NuGet: Tomlyn
        public static CodedConfig LoadToml(string filePath)
        {
            var toml = System.IO.File.ReadAllText(filePath);
            return Tomlyn.TomlSerializer.Deserialize<CodedConfig>(toml);
        }
    }

    public class SettingsConfig
    {
        public string OrchestratorQueueName { get; set; } = "";
        public string OrchestratorQueueNameTyped { get; set; } = "";
        public string OrchestratorFolderPath { get; set; } = "";
        public string OrchestratorFolderPathTyped { get; set; } = "";
        public int MaxItemsPerRun { get; set; }
        public int MaxItemsPerRunTyped { get; set; }
        public int RetryCount { get; set; }
        public int RetryCountTyped { get; set; }
        public string LogPrefix { get; set; } = "";
        public string LogPrefixTyped { get; set; } = "";

        public override string ToString() =>
            $"SettingsConfig {{ OrchestratorQueueName={OrchestratorQueueName}, OrchestratorQueueNameTyped={OrchestratorQueueNameTyped}, OrchestratorFolderPath={OrchestratorFolderPath}, OrchestratorFolderPathTyped={OrchestratorFolderPathTyped}, MaxItemsPerRun={MaxItemsPerRun}, MaxItemsPerRunTyped={MaxItemsPerRunTyped}, RetryCount={RetryCount}, RetryCountTyped={RetryCountTyped}, LogPrefix={LogPrefix}, LogPrefixTyped={LogPrefixTyped} }}";
    }

    public class ConstantsConfig
    {
        public int MaxRetryNumber { get; set; }
        public int MaxRetryNumberTyped { get; set; }
        public int MaxConsecutiveSystemExceptions { get; set; }
        public int MaxConsecutiveSystemExceptionsTyped { get; set; }
        public int RetryNumberGetTransactionItem { get; set; }
        public int RetryNumberGetTransactionItemTyped { get; set; }

        public override string ToString() =>
            $"ConstantsConfig {{ MaxRetryNumber={MaxRetryNumber}, MaxRetryNumberTyped={MaxRetryNumberTyped}, MaxConsecutiveSystemExceptions={MaxConsecutiveSystemExceptions}, MaxConsecutiveSystemExceptionsTyped={MaxConsecutiveSystemExceptionsTyped}, RetryNumberGetTransactionItem={RetryNumberGetTransactionItem}, RetryNumberGetTransactionItemTyped={RetryNumberGetTransactionItemTyped} }}";
    }

    public class AssetsConfig
    {
        public object? CredentialM365 { get; set; }
        public object? CredentialFtp { get; set; }

        public override string ToString() =>
            $"AssetsConfig {{ CredentialM365={CredentialM365}, CredentialFtp={CredentialFtp} }}";
    }
}