// <auto-generated>
//     Generated by ConFigTree 0.2.0
//     https://rpapub.github.io/ConFigTree/
// </auto-generated>

#nullable enable

using System;
using System.Data;
using System.Collections.Generic;

namespace Cpmf.Config
{
    /// <summary>Root configuration object.</summary>
    public class CodedConfig
    {
        public SettingsConfig Settings { get; set; } = new();
        public ClassicAssetsConfig ClassicAssets { get; set; } = new();
        public EmptyValueTypeConfig EmptyValueType { get; set; } = new();
        public ExtraColumnConfig ExtraColumn { get; set; } = new();
        public override string ToString() =>
            $"CodedConfig {{ Settings={Settings}, ClassicAssets={ClassicAssets}, EmptyValueType={EmptyValueType}, ExtraColumn={ExtraColumn} }}";

        public static CodedConfig Load(Dictionary<string, DataTable> tables)
        {
            var cfg = new CodedConfig();
            if (tables.TryGetValue("Settings", out var t_Settings)) cfg.Settings = SettingsConfig.FromDataTable(t_Settings);
            // "ClassicAssets", "EmptyValueType", "ExtraColumn": asset values are fetched from Orchestrator via GetRobotAsset in the generated XAML snippet — not loaded from DataTable.
            return cfg;
        }
    }

    public class SettingsConfig
    {
        /// <summary>Deployment environment.</summary>
        public string Environment { get; set; } = "UAT";

        public static SettingsConfig FromDataTable(DataTable dt)
        {
            var cfg = new SettingsConfig();
            foreach (DataRow row in dt.Rows)
            {
                if (row.ItemArray.Length < 2) continue;
                var key   = row[0]?.ToString()?.Trim();
                var value = row[1]?.ToString()?.Trim() ?? "";
                switch (key)
                {
                    case "Environment": cfg.Environment = value; break;
                }
            }
            return cfg;
        }

        public override string ToString() =>
            $"SettingsConfig {{ Environment={Environment} }}";
    }

    public class ClassicAssetsConfig
    {
        /// <summary>Input queue name.</summary>
        public object? QueueName { get; set; }
        /// <summary>REST API base URL.</summary>
        public object? ApiEndpoint { get; set; }

        public override string ToString() =>
            $"ClassicAssetsConfig {{ QueueName={QueueName}, ApiEndpoint={ApiEndpoint} }}";
    }

    public class EmptyValueTypeConfig
    {
        /// <summary>SAP credential.</summary>
        public object? CredentialSap { get; set; }
        /// <summary>M365 credential.</summary>
        public object? CredentialM365 { get; set; }

        public override string ToString() =>
            $"EmptyValueTypeConfig {{ CredentialSap={CredentialSap}, CredentialM365={CredentialM365} }}";
    }

    public class ExtraColumnConfig
    {
        /// <summary>API key asset.</summary>
        public string ApiKey { get; set; } = "";
        /// <summary>Max items asset.</summary>
        public int MaxItems { get; set; }

        public override string ToString() =>
            $"ExtraColumnConfig {{ ApiKey={ApiKey}, MaxItems={MaxItems} }}";
    }
}